export const dashboardHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Algobot · Collection desk</title><link rel="stylesheet" href="/dashboard.css"></head>
<body><header><div><p class="eyebrow">ALGOBOT / RESEARCH</p><h1>Collection desk</h1></div><a href="https://algobot.fun/" target="_blank" rel="noopener">Open game ↗</a></header>
<main><section id="login"><h2>Your collection, in one place.</h2><p>Check received datasets and upload errors. Sign in with the administrator key used for research downloads.</p><form id="login-form"><label for="key">Administrator key</label><input id="key" type="password" autocomplete="off" required><button type="submit">Open collection</button></form><p class="muted">The key stays in this tab’s memory and is cleared when you sign out or reload.</p><p id="login-error" role="alert"></p></section>
<section id="desk" hidden><div class="toolbar"><p id="summary">Loading collection…</p><div><button id="refresh">Refresh now</button><button id="logout" class="secondary">Sign out</button></div></div><p id="updated" class="muted" role="status"></p><p id="notice" role="alert"></p>
<nav aria-label="Collection views"><button id="datasets-tab" aria-pressed="true">Datasets</button><button id="errors-tab" aria-pressed="false" class="secondary">Upload errors</button></nav>
<div class="filters"><label for="search">Participant or file<input id="search" type="search" placeholder="e.g. P017"></label><label class="check"><input id="qa" type="checkbox"> Include QA tests</label><label class="check"><input id="auto" type="checkbox" checked> Refresh every minute</label></div>
<section id="datasets"><h2>Received datasets</h2><p class="muted">Newest uploads first. “Uploaded” is the storage receipt time, not proof that a player has finished. Times use your device timezone.</p><div class="table-wrap"><table><thead><tr><th>Participant</th><th>Round / file</th><th>Uploaded</th><th>Size</th><th><span class="sr-only">Download</span></th></tr></thead><tbody id="files"></tbody></table></div><p id="files-empty" hidden>No datasets match these filters.</p></section>
<section id="errors" hidden><div class="toolbar"><h2>Upload errors</h2><label for="hours">Time window <select id="hours"><option value="1">Last hour</option><option value="24" selected>Last 24 hours</option><option value="72">Last 3 days</option></select></label></div><p class="muted">Application errors and platform failures from the upload Worker. Older failures may have no participant code. Logs can arrive with a short delay.</p><p id="error-status" role="status"></p><div class="table-wrap"><table><thead><tr><th>Time</th><th>Participant</th><th>Error</th><th>Request</th></tr></thead><tbody id="error-rows"></tbody></table></div></section>
</section></main><footer>Algobot collection tools · Read-only access. No datasets or logs are changed here.</footer><script src="/dashboard.js" defer></script></body></html>`;

export const dashboardCSS = `:root{font-family:system-ui,sans-serif;color:#334155;background:#f3f4f6;font-size:15px}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0}header,main,footer{max-width:1220px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #64748b}h1{margin:3px 0;font-size:30px}h2{font-size:21px;margin:16px 0}.eyebrow{font-size:12px;font-weight:750;letter-spacing:.06em;color:#166534;margin:0}a{color:#166534}p{line-height:1.6}.muted,footer{color:#475569;font-size:13px}#login{max-width:560px;margin:50px auto;padding:28px;background:white;border:2px solid #64748b;border-radius:12px}label{display:block;font-weight:600}input,select,button{font:inherit;border:2px solid #64748b;border-radius:6px;padding:10px 12px}input,select{background:#fff;color:#334155}input[type=password],input[type=search]{display:block;width:100%;margin:8px 0 16px}button{white-space:nowrap;cursor:pointer;background:#bbf7d0;color:#334155;font-weight:650}button.secondary{background:#fff}button:disabled{cursor:wait;opacity:.65}:focus-visible{outline:3px solid #166534;outline-offset:3px}.toolbar,.filters{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.toolbar>div{display:flex;gap:10px}.filters{margin:24px 0;justify-content:flex-start}.filters>label:first-child{flex:1;min-width:200px}.check{display:flex;align-items:center;gap:6px;font-size:13px}nav{display:flex;gap:8px;padding:16px 0;border-bottom:1px solid #cbd5e1}table{min-width:760px;width:100%;border-collapse:collapse;background:white;text-align:left}th{background:#e5e7eb;font-size:13px}th,td{padding:14px 12px;border-bottom:1px solid #cbd5e1;vertical-align:top}td{overflow-wrap:anywhere}td:first-child{font-weight:600}.table-wrap{overflow-x:auto;border:2px solid #64748b;border-radius:8px}td small{display:block;margin-top:4px;color:#475569}#notice,#login-error{color:#991b1b}#error-status{background:#fff;padding:12px;border-left:4px solid #64748b}footer{border-top:1px solid #cbd5e1;margin-top:32px}.sr-only{position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:600px){header,main,footer{padding:16px}header{align-items:flex-start;gap:16px}h1{font-size:25px}#login{margin:20px 0;padding:20px}th,td{padding:10px 8px;font-size:13px}.filters{gap:8px}.filters>label:first-child{flex-basis:100%}.toolbar>div{width:100%}.toolbar button{flex:1}table{min-width:760px}}`;

export const dashboardJS = String.raw`
const $=id=>document.getElementById(id);
let token='',files=[],errors=[],generation=0,busy=false;
const bytes=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB';
const time=value=>new Date(value).toLocaleString();
function cell(row,text){const td=document.createElement('td');td.textContent=text??'Unknown';row.append(td);return td;}
function matches(participant,key=''){return ($('qa').checked||!/^QA[_-]/i.test(participant))&&(participant+' '+key).toLowerCase().includes($('search').value.trim().toLowerCase());}
async function api(path){const response=await fetch(path,{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok){if(response.status===403)throw Error('Administrator key was not accepted.');const body=await response.json().catch(()=>({}));throw Error(body.error||'Request failed ('+response.status+').');}return response;}
function render(){
 $('files').replaceChildren();const selected=files.filter(f=>matches(f.key.split('/')[1]||'',f.key));
 for(const f of selected){const row=document.createElement('tr'),parts=f.key.split('/');cell(row,parts[1]||'Unknown');cell(row,parts[0]+' / '+parts.slice(2).join('/'));const uploaded=cell(row,time(f.uploaded));uploaded.title=f.uploaded;cell(row,bytes(f.size));const action=cell(row,'');const button=document.createElement('button');button.textContent='Download';button.className='secondary';button.setAttribute('aria-label','Download '+f.key);button.onclick=()=>download(f,button);action.append(button);$('files').append(row);}
 $('files-empty').hidden=selected.length>0;$('summary').textContent=selected.length+' files · '+bytes(selected.reduce((sum,f)=>sum+f.size,0));
 $('error-rows').replaceChildren();for(const e of errors.filter(e=>matches(e.participant||'',e.reason))){const row=document.createElement('tr');cell(row,time(e.timestamp));cell(row,e.participant||'Not recorded');cell(row,e.reason+(e.status?' · HTTP '+e.status:''));cell(row,e.requestId||'Not recorded');$('error-rows').append(row);}
}
async function download(file,button){const epoch=generation;button.disabled=true;try{const blob=await(await api('/admin/file?key='+encodeURIComponent(file.key))).blob();if(epoch!==generation)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.key.replaceAll('/','_');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){if(epoch===generation)$('notice').textContent=error.message;}finally{button.disabled=false;}}
async function refresh(){if(busy||!token)return;busy=true;const epoch=generation;$('refresh').disabled=true;$('notice').textContent='';
 try{const result=await(await api('/admin/list')).json();if(epoch!==generation)return;files=result.objects.sort((a,b)=>Date.parse(b.uploaded)-Date.parse(a.uploaded));render();$('updated').textContent='Dataset list checked '+new Date().toLocaleTimeString();}
 catch(error){if(epoch===generation)$('notice').textContent=error.message;}
 if(epoch!==generation)return;
 try{const result=await(await api('/admin/errors?hours='+$('hours').value)).json();if(epoch!==generation)return;errors=result.errors;render();$('error-status').textContent=result.limited?'Showing the latest '+errors.length+' failures. Narrow the time window for more detail.':errors.length+' recorded failures before participant/QA filters. Checked '+new Date().toLocaleTimeString()+'.';}
 catch(error){if(epoch===generation){errors=[];render();$('error-status').textContent=error.message;}}
 finally{if(epoch===generation){busy=false;$('refresh').disabled=false;}}
}
$('login-form').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;token=$('key').value;try{await api('/admin/list');$('key').value='';$('login-error').textContent='';$('login').hidden=true;$('desk').hidden=false;await refresh();}catch(error){token='';$('login-error').textContent=error.message;}finally{button.disabled=false;}};
$('logout').onclick=()=>{generation++;busy=false;$('refresh').disabled=false;token='';files=[];errors=[];render();$('desk').hidden=true;$('login').hidden=false;$('key').value='';$('key').focus();};
$('refresh').onclick=refresh;$('hours').onchange=refresh;$('search').oninput=render;$('qa').onchange=render;
for(const view of ['datasets','errors'])$(view+'-tab').onclick=()=>{for(const name of ['datasets','errors']){$(name).hidden=name!==view;$(name+'-tab').setAttribute('aria-pressed',String(name===view));$(name+'-tab').className=name===view?'':'secondary';}};
setInterval(()=>{if($('auto').checked&&!document.hidden)void refresh();},60000);
`;
