export const BLOCK_LABELS = {
  "say": "Say",
  "jump": "Jump to column",
  "up": "Move up",
  "down": "Move down",
  "left": "Move left",
  "right": "Move right",
  "wait": "Wait seconds",
  "till": "Prepare soil",
  "water": "Water soil",
  "harvest": "Harvest crop",
  "plant": "Plant",
  "destroy": "Remove crop",
  "kill_bug": "Remove pest",
  "extinguish": "Put out fire",
  "is_tilled": "Is the soil prepared?",
  "is_watered": "Is the soil wet?",
  "is_planted": "Is there a crop?",
  "is_harvestable": "Is the crop ready?",
  "is_bug": "Is there a pest?",
  "is_fire": "Is there a fire?",
  "is_dead": "Is the crop spoiled?",
  "columns": "Number of columns",
  "rows": "Number of rows"
};
