export const INTRODUCTION_STORY = [
  { title: "A farm that follows your ideas", text: "Welcome! I’m your Bot Teacher. In Algobot, you build a program with blocks to tell your robot how to care for a farm. Later, you can write the same commands as code. Let’s watch a small farm together.", code: ["// Your instructions become the robot’s actions"], action: "welcome" },
  { title: "One command, one action", text: "This is Bot 0. It follows instructions in order. Watch bot.right() move it one tile. Planning that order is the beginning of an algorithm.", code: ["bot.right();"], action: "move" },
  { title: "Prepare, then plant", text: "First loosen the soil, then plant a seed. Order matters: a seed needs prepared soil. Each crop you plant normally uses one seed from your inventory.", code: ["bot.till();", 'bot.plant("wheat");'], action: "plant" },
  { title: "Care makes crops grow", text: "Water soaks into the soil and feeds the wheat. When the soil dries, water again. Watch the crop change from a seedling into ripe wheat.", code: ["bot.water();", "// Wait for the soil to dry", "bot.water();"], action: "water" },
  { title: "Your harvest earns its keep", text: "Harvest ripe crops to earn coins and experience. Coins buy seeds and farm upgrades; experience helps you level up. These example earnings belong to this introduction—your own starting supplies stay safe.", code: ["bot.harvest();"], action: "harvest" },
  { title: "Ripe does not mean forever", text: "Now watch a crop we leave behind. Its freshness falls, then it rots and releases green gas. Harvest on time! We shorten the wait here so you can see the whole change.", code: ["// No harvest: fresh → expiring → rotten"], action: "spoil" },
  { title: "More helpers, better plans", text: "As you progress, you can unlock more robots. Each bot runs its own program. Watch Bots 0 and 1 take different jobs. Loops repeat work; conditions help your bots decide when a crop needs care.", code: ["// Bot 0", "bot.down();", "bot.till();", "// Bot 1", "bot.right();", "bot.right();", "bot.till();"], action: "bots" },
  { title: "Rain lends a hand", text: "Your farm can change while your program runs. Rain clouds travel over the farm and drop water onto the soil. Rain helps crops grow and can also put out fire.", code: ["// Rain waters the soil for you"], action: "rain" },
  { title: "Protect what you grow", text: "A crowded farm can catch fire. Flames grow, spread and destroy crops. Your bot can extinguish a burning tile. Watch Bot 0 put this fire out before it grows.", code: ["// On a burning tile", "bot.extinguish();"], action: "fire" },
  { title: "An uninvited guest", text: "Pests can damage ripe crops too. This bug has found our wheat. Move a bot onto the same tile and use bot.kill_bug() to remove it. Conditions will help you check for trouble before acting.", code: ["// On a tile with a pest", "bot.kill_bug();"], action: "pest" },
  { title: "Your first little program", text: "You don’t need to automate everything at once. Follow your current mission, try a command, and watch what happens. Your first practice tasks are protected from hazards and spoilage. I’ll help you build from there.", code: ["bot.right();", "// Your first mission starts with this one block"], action: "finish" },
];
