export const QUEST_PATH_VERSION = "guided-v2";
export const QuestTypes = { TUTORIAL: "tutorial", CROP: "crop", CS_CONCEPT: "cs_concept", SHOP: "shop" };
const quest = (chapter, title, description, tip, prereq, extra = {}) => ({
  type: QuestTypes.CS_CONCEPT, chapter, title, description, tip,
  goal: 1, rewards: { exp: 40, coins: 30 }, prereq: prereq ? [prereq] : [], ...extra,
});
const reward = (unlocks, coins = 40) => ({ exp: 50, coins, unlocks });

// Existing IDs keep older quest_attempts exports readable.
export const QUEST_DATA = {
  intro_run: quest(1, "Add your first block", "Add Move right. Press Start.", "Open 🤖 Bot.", null,
    { type: QuestTypes.TUTORIAL, rewards: { exp: 10, coins: 15 } }),
  intro_build: quest(1, "Give your robot a direction", "Add Move down. Press Start.", "Open 🤖 Bot.", "intro_run",
    { type: QuestTypes.TUTORIAL, rewards: { exp: 15, coins: 20, unlocks: ["is_tilled", "is_planted", "rows", "columns"] } }),
  intro_say: quest(1, "Say hello", "Use Say to show a message.", "Open 🤖 Bot.", "intro_build", { type: QuestTypes.TUTORIAL, rewards: { exp: 15, coins: 10 } }),
  intro_sequence: quest(1, "Two blocks, one trip", "Connect Move left and Move right. Run them together.", "Start away from the left edge.", "intro_say", { type: QuestTypes.TUTORIAL, goal: 2, rewards: { exp: 20, coins: 15 } }),
  tut_2: quest(2, "Take your first farming steps", "Prepare soil, plant wheat, water, then harvest.", "Open 🌾 Farm.", "intro_sequence",
    { type: QuestTypes.TUTORIAL, goal: 4, rewards: { exp: 30, coins: 30, unlocks: ["is_watered", "is_harvestable", "buy_seed"] } }),
  shop_seed_0: quest(2, "Buy more seeds", "Buy wheat seeds from the shop.", "Open 💰 Shop.", "tut_2", { type: QuestTypes.SHOP }),
  farm_two_0: quest(2, "Plant two tiles", "Plant wheat on two tiles in one run. Finish the run with no errors. If an error occurs, fix it and try again.", "Add Prepare soil from 🌾 Farm.", "shop_seed_0", { goal: 2, setup: "two-bare" }),
  intro_loop: quest(3, "Use a loop for two trips", "Repeat Move left and Move right twice.", "Open 🔁 Loops. A loop repeats its inside blocks.", "farm_two_0", { goal: 2, concept: "for", setup: "movement" }),
  loop_row_0: quest(3, "Plant a row", "Use repeat to plant three wheat tiles. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔁 Loops. Set repeat to 3.", "intro_loop", { goal: 3, setup: "row-bare" }),
  loop_water_0: quest(3, "Water the row", "Use repeat to water three crops. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔁 Loops. Put Water soil inside repeat.", "loop_row_0", { goal: 3, setup: "row-young" }),
  crop_wheat_1: quest(3, "Harvest three wheat crops", "Harvest three wheat crops with a loop. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔁 Loops. Put Harvest crop inside repeat.", "loop_water_0", { type: QuestTypes.CROP, goal: 3, setup: "row-ready", program: true }),
  cs_check_0: quest(4, "Ask your robot a question", "Say whether this tile has a crop. true means yes; false means no.", "Open 🔍 Check.", "crop_wheat_1"),
  if_ready_0: quest(4, "Harvest if ready", "Use if to harvest a ready crop. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔢 Logic. Put Is the crop ready? inside if.", "cs_check_0", { setup: "ready" }),
  cs_if_0: quest(4, "Plant if the tile is empty", "Plant wheat if there is no crop. not changes yes into no.", "Open 🔢 Logic. Find not.", "if_ready_0", { setup: "empty", concept: "if", rewards: reward(["is_dead"]) }),
  if_else_0: quest(4, "Harvest or water", "Harvest ready crops; otherwise, water them. Run both choices. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔢 Logic. Add else to if using its gear.", "cs_if_0", { goal: 2, setup: "mixed" }),
  if_row_0: quest(4, "Check the whole row", "Repeat a ready check across three crops. Harvest each ready crop. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔁 Loops. Put if inside repeat.", "if_else_0", { goal: 3, setup: "row-ready" }),
  cs_cleanup_0: quest(4, "Clear a spoiled crop", "Check for a spoiled crop. Remove it if spoiled. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔍 Check. Find Is the crop spoiled?.", "if_row_0", { setup: "dead", rewards: reward(["corn"]) }),
  cs_grid_0: quest(5, "Count your farm rows", "Use Say to show the number of rows.", "Open 🔣 Math. Find Number of rows.", "cs_cleanup_0", { rewards: reward(["buy_row", "buy_column"], 120) }),
  shop_land_0: quest(5, "Make your farm bigger", "Buy one row or column.", "Open 💰 Shop.", "cs_grid_0", { type: QuestTypes.SHOP }),
  loop_size_0: quest(5, "Fit a loop to your farm", "Use the column count to water a whole row. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔣 Math. Find Number of columns.", "shop_land_0", { setup: "wide-young", rewards: reward(["upgrade_bot_action", "upgrade_bot_move", "upgrade_bot_check", "bot"], 120) }),
  shop_upgrade_0: quest(5, "Speed up your robot", "Buy one robot speed upgrade.", "Open 💰 Shop.", "loop_size_0", { type: QuestTypes.SHOP, rewards: reward(["rice"]) }),
  var_set_0: quest(6, "Remember a number", "Set count to 0. Say count. A variable remembers a value. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 📦 Variables. Create count.", "shop_upgrade_0"),
  var_change_0: quest(6, "Count up", "Set count to 0. Repeat adding 1 three times. Say count. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 📦 Variables. Find change.", "var_set_0"),
  var_harvest_0: quest(6, "Count your harvest", "Count three successful harvests in a loop. Say the total. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 📦 Variables. Create harvested.", "var_change_0", { setup: "row-ready" }),
  var_crop_0: quest(6, "Pick your crop once", "Set crop to corn. Plant using that variable. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 📦 Variables. Create crop.", "var_harvest_0", { setup: "empty", rewards: reward(["potato"]) }),
  logic_compare_0: quest(7, "Check your seed count", "Plant wheat if your seed count is greater than 0. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔢 Logic. Find the comparison block.", "var_crop_0", { setup: "empty" }),
  logic_and_0: quest(7, "Combine two checks", "Plant if the soil is prepared and empty. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔢 Logic. Find and.", "logic_compare_0", { setup: "empty", rewards: reward(["randint", "randfloat"]) }),
  cs_random_0: quest(7, "Choose a crop at random", "Pick 1 or 2. Plant wheat for 1; otherwise, plant corn. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔣 Math. Find Random whole number from.", "logic_and_0", { setup: "empty", rewards: reward(["jump"]) }),
  cs_jump_0: quest(7, "Jump using a counter", "Use count in a loop. Jump to columns 0, 1, and 2. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 📦 Variables. Set count to 0.", "cs_random_0", { rewards: reward(["sugarcane"]) }),
  cs_wait_0: quest(8, "Wait until ready", "While the crop is not ready, wait 1 second. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔁 Loops. Find repeat while.", "cs_jump_0", { setup: "growing" }),
  for_count_0: quest(8, "Count with for", "Use count with to visit every column in one row. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔁 Loops. Columns start at 0.", "cs_wait_0"),
  loop_farm_0: quest(8, "Visit the whole farm", "Use a loop inside another loop. Water every farm tile. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔁 Loops. Count rows outside and columns inside.", "for_count_0", { setup: "farm-young", rewards: reward(["tomato"]) }),
  fn_define_0: quest(9, "Name your steps", "Make care for tile: prepare soil, plant wheat, water. Call it. Finish the run with no errors. If an error occurs, fix it and try again.", "Open ⚙️ Functions. Name your function care for tile.", "loop_farm_0", { setup: "bare" }),
  fn_reuse_0: quest(9, "Use your function everywhere", "Call care for tile inside your whole-farm loop. Finish the run with no errors. If an error occurs, fix it and try again.", "Open ⚙️ Functions. Find your function's call block.", "fn_define_0", { setup: "farm-bare" }),
  fn_param_0: quest(9, "Give a function an input", "Make plant row with a crop input. Plant a corn row. Finish the run with no errors. If an error occurs, fix it and try again.", "Open ⚙️ Functions. Add an input using the function's gear.", "fn_reuse_0", { setup: "wide-bare" }),
  fn_return_0: quest(9, "Return an answer", "Make is empty tile return a check. Say its answer. Finish the run with no errors. If an error occurs, fix it and try again.", "Open ⚙️ Functions. Choose the function with a return slot.", "fn_param_0", { optional: true, setup: "empty" }),
  list_crops_0: quest(10, "Plant a crop list", "Use a list to plant wheat, corn, then rice. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 📋 Arrays. Find create list with.", "fn_param_0", { setup: "row-bare" }),
  hazard_bug_0: quest(10, "Patrol for bugs", "Check every tile using loops. Remove each bug you find. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔍 Check. Find Is there a pest?.", "list_crops_0", { setup: "bugs" }),
  hazard_fire_0: quest(10, "Put out fires", "Check every tile using loops. Put out each fire. Finish the run with no errors. If an error occurs, fix it and try again.", "Open 🔍 Check. Find Is there a fire?.", "hazard_bug_0", { setup: "fires" }),
  crop_corn_1: quest(4, "Harvest three corn crops", "Harvest three corn crops whenever you like.", "Open 🌾 Farm. Choose Plant corn.", "cs_cleanup_0", { type: QuestTypes.CROP, optional: true, goal: 3 }),
  crop_rice_1: quest(5, "Harvest three rice crops", "Harvest three rice crops whenever you like.", "Open 🌾 Farm. Choose Plant rice.", "shop_upgrade_0", { type: QuestTypes.CROP, optional: true, goal: 3 }),
  crop_potato_1: quest(6, "Harvest three potato crops", "Harvest three potato crops whenever you like.", "Open 🌾 Farm. Choose Plant potato.", "var_crop_0", { type: QuestTypes.CROP, optional: true, goal: 3 }),
  crop_sugarcane_1: quest(7, "Harvest three sugarcane crops", "Harvest three sugarcane crops. Water them again after harvesting.", "Open 🌾 Farm. Choose Plant sugarcane.", "cs_jump_0", { type: QuestTypes.CROP, optional: true, goal: 3 }),
  crop_tomato_1: quest(8, "Harvest three tomato crops", "Harvest three tomato crops whenever you like.", "Open 🌾 Farm. Choose Plant tomato.", "loop_farm_0", { type: QuestTypes.CROP, optional: true, goal: 3 }),
};
