import { CropTypes } from "./enum.js";
import { PLAYER_DATA, INVENTORY } from "./global.js";

export const QuestTypes = {
  TUTORIAL: "tutorial",
  CROP: "crop",
  CS_CONCEPT: "cs_concept",
  SHOP: "shop"
};

export const QUEST_DATA = {
  // Tutorial Quests
  "intro_run": {
    type: QuestTypes.TUTORIAL, title: "Add your first block",
    description: "Drag bot.right from Bot into the work area, then press Start.",
    tip: "You choose the block. The robot follows it when you press Start.",
    goal: 1, rewards: { exp: 10, coins: 15 }, prereq: [],
  },
  "intro_build": {
    type: QuestTypes.TUTORIAL, title: "Give your robot a direction",
    description: "Remove bot.right. Add bot.down from Bot, then press Start.",
    tip: "Drag bot.down from Bot into the workspace and run it.",
    goal: 1, rewards: { exp: 15, coins: 20, unlocks: ["is_tilled", "is_planted", "rows", "columns"] },
    prereq: ["intro_run"],
  },
  "intro_say": {
    type: QuestTypes.TUTORIAL, title: "Say hello",
    description: "Add bot.say, type a short message, then press Start.",
    tip: "Click the text inside bot.say and type Hello! Your robot will show it.",
    goal: 1, rewards: { exp: 15, coins: 10 }, prereq: ["intro_build"],
  },
  "intro_sequence": {
    type: QuestTypes.TUTORIAL, title: "Two blocks, one trip",
    description: "Connect bot.left and bot.right. Run them to go left, then back.",
    tip: "Snap the blocks together. Your robot follows them from top to bottom. Start away from the left edge.",
    goal: 2, rewards: { exp: 20, coins: 15 }, prereq: ["intro_say"],
  },
  "tut_2": {
    type: QuestTypes.TUTORIAL,
    title: "First Steps in Farming",
    description: "Till, plant, water, and harvest wheat.",
    tip: 'Open Farm. Till, plant wheat, then water. Water again when the soil dries. Harvest when the wheat is ready.',
    goal: 4,
    rewards: { exp: 30, coins: 30, unlocks: ["is_watered", "is_harvestable"] },
    prereq: ["intro_sequence"],
  },

  // CS Concept Quests
  "intro_loop": {
    type: QuestTypes.CS_CONCEPT,
    title: "Do the trip twice",
    description: "Repeat your left-and-right trip twice.",
    tip: 'Open Loops. Set repeat to 2 and put bot.left then bot.right inside. A loop repeats the blocks inside it.',
    concept: "for",
    goal: 2,
    rewards: { exp: 50, coins: 40, unlocks: ["buy_seed", "buy_row", "buy_column"] },
    prereq: ["tut_2"],
  },
  "cs_if_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Check before you harvest",
    description: "Use if to harvest only when a crop is ready.",
    tip: 'In Logic category, use if statement with bot.is_harvestable from Check category to harvest ready crops.',
    concept: "if",
    goal: 1,
    rewards: { exp: 50, coins: 40, unlocks: ["jump", "is_dead"] },
    prereq: ["intro_loop"],
  },
  "cs_grid_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Tell us about your farm",
    description: "Use bot.say to show how many rows your farm has.",
    tip: 'Put rows from Math inside bot.say from Bot. Press Start to see the number. In text: bot.say(rows());',
    goal: 1,
    rewards: { exp: 60, coins: 50, unlocks: ["upgrade_bot_action", "upgrade_bot_move", "upgrade_bot_check", "bot"] },
    prereq: ["cs_if_0"],
  },
  "cs_jump_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Jump to a tile",
    description: "Jump directly to specific tile coordinates.",
    tip: 'In Bot category, use bot.jump to teleport directly to any valid grid coordinate.',
    goal: 1,
    rewards: { exp: 70, coins: 60 },
    prereq: ["cs_grid_0"],
  },
  "cs_cleanup_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Clear a spoiled crop",
    description: "Inspect for withered plants and clear them.",
    tip: 'In Check category, use bot.is_dead inside an if statement, then call bot.destroy from Farm category.',
    goal: 1,
    rewards: { exp: 100, coins: 90, unlocks: ["wait"] },
    prereq: ["cs_if_0"],
  },
  "cs_wait_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Wait a moment",
    description: "Pause bot execution while crops develop.",
    tip: 'In Bot category, use bot.wait to pause execution while waiting for crop growth.',
    goal: 1,
    rewards: { exp: 110, coins: 100, unlocks: ["randint", "randfloat"] },
    prereq: ["cs_cleanup_0"],
  },
  "cs_random_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Try a random number",
    description: "Generate random numbers for non deterministic farm logic.",
    tip: 'In Math category, use randint or randfloat to create dynamic decision thresholds.',
    goal: 1,
    rewards: { exp: 120, coins: 110 },
    prereq: ["cs_wait_0"],
  },

  // Dedicated Shop Quests
  "shop_seed_0": {
    type: QuestTypes.SHOP,
    title: "Buy more seeds",
    description: "Purchase seed packs from the shop.",
    tip: 'In Shop category, use shop.buy_seed or purchase seeds directly in the shop interface.',
    goal: 1,
    rewards: { exp: 40, coins: 25 },
    prereq: ["intro_loop"],
  },
  "shop_land_0": {
    type: QuestTypes.SHOP,
    title: "Make your farm bigger",
    description: "Expand farm size by buying a row or column.",
    tip: 'In Shop category, use shop.buy_row or shop.buy_column to increase grid capacity for larger loops.',
    goal: 1,
    rewards: { exp: 75, coins: 50 },
    prereq: ["cs_grid_0"],
  },
  "shop_upgrade_0": {
    type: QuestTypes.SHOP,
    title: "Speed up your robot",
    description: "Purchase a speed upgrade for your bot.",
    tip: 'In Shop category, use shop.upgrade_bot_action or shop.upgrade_bot_move to execute algorithms faster.',
    goal: 1,
    rewards: { exp: 100, coins: 75 },
    prereq: ["shop_land_0"],
  },

  // Crop Quests
  "crop_wheat_1": {
    type: QuestTypes.CROP,
    title: "Wheat Harvest Mastery",
    description: "Harvest wheat 5 times.",
    tip: 'In Loops category, combine repeat block with bot.till, bot.plant wheat, bot.water, and bot.harvest.',
    goal: 5,
    rewards: { exp: 50, coins: 30, unlocks: [CropTypes.CORN] },
    prereq: ["tut_2"],
  },
  "crop_corn_1": {
    type: QuestTypes.CROP,
    title: "Corn Cluster Harvesting",
    description: "Harvest corn 10 times.",
    tip: 'In Farm category, use bot.plant corn to place corn in adjacent clusters for growth synergy.',
    goal: 10,
    rewards: { exp: 100, coins: 60, unlocks: [CropTypes.RICE] },
    prereq: ["crop_wheat_1"],
  },
  "crop_rice_1": {
    type: QuestTypes.CROP,
    title: "High Yield Rice Cultivation",
    description: "Harvest rice 10 times.",
    tip: 'In Farm and Check categories, combine bot.plant rice with bot.is_bug to protect high profit crops.',
    goal: 10,
    rewards: { exp: 150, coins: 90, unlocks: [CropTypes.POTATO] },
    prereq: ["crop_corn_1"],
  },
  "crop_potato_1": {
    type: QuestTypes.CROP,
    title: "Potato Underground Farming",
    description: "Harvest potato 10 times.",
    tip: 'In Farm and Bot categories, use bot.plant potato and bot.wait to manage slow growing tuber cycles.',
    goal: 10,
    rewards: { exp: 200, coins: 120, unlocks: [CropTypes.SUGARCANE] },
    prereq: ["crop_rice_1"],
  },
  "crop_sugarcane_1": {
    type: QuestTypes.CROP,
    title: "Sugarcane Regrowth Loop",
    description: "Harvest sugarcane 10 times.",
    tip: 'In Loops category, use while loop with bot.harvest to continuously harvest regrowing sugarcane.',
    goal: 10,
    rewards: { exp: 250, coins: 150, unlocks: [CropTypes.TOMATO] },
    prereq: ["crop_potato_1"],
  },
  "crop_tomato_1": {
    type: QuestTypes.CROP,
    title: "Fresh Tomato Harvesting",
    description: "Harvest tomato 10 times.",
    tip: 'In Check category, use bot.is_harvestable inside a fast inspection loop to harvest tomatoes before spoilage.',
    goal: 10,
    rewards: { exp: 300, coins: 200 },
    prereq: ["crop_sugarcane_1"],
  }
};
