import { CropTypes } from "./enum.js";
import { PLAYER_DATA, INVENTORY } from "./global.js";

export const QuestTypes = {
  TUTORIAL: "tutorial",
  CROP: "crop",
  CS_CONCEPT: "cs_concept",
  SHOP: "shop"
};

export const QUEST_DATA = {
  // Tutorial Quests
  "tut_0": {
    type: QuestTypes.TUTORIAL,
    title: "Welcome to AlgoBot",
    description: "Make your bot say a greeting message.",
    tip: 'In Bot category, use bot.say to make your bot speak.',
    goal: 1,
    rewards: { exp: 10, coins: 15 },
    prereq: [],
  },
  "tut_1": {
    type: QuestTypes.TUTORIAL,
    title: "Movement Basics",
    description: "Move your bot across farm tiles 3 times.",
    tip: 'In Bot category, use bot.right or bot.down to navigate tiles.',
    goal: 3,
    rewards: { exp: 15, coins: 20, unlocks: ["is_tilled", "is_planted", "rows", "columns"] },
    prereq: ["tut_0"],
  },
  "tut_2": {
    type: QuestTypes.TUTORIAL,
    title: "First Steps in Farming",
    description: "Till, plant, water, and harvest wheat.",
    tip: 'In Farm category, sequence bot.till, bot.plant wheat, bot.water, and bot.harvest.',
    goal: 4,
    rewards: { exp: 30, coins: 30, unlocks: ["is_watered", "is_harvestable"] },
    prereq: ["tut_1"],
  },

  // CS Concept Quests
  "cs_loop_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Loop Automation",
    description: "Execute a repeat loop to automate farm actions.",
    tip: 'In Loops category, use repeat block or write for (var i = 0; i < 3; i++) to repeat actions.',
    concept: "for",
    goal: 1,
    rewards: { exp: 50, coins: 40, unlocks: ["buy_seed", "buy_row", "buy_column"] },
    prereq: ["tut_2"],
  },
  "cs_if_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Conditional Crop Inspection",
    description: "Inspect crop state using an if conditional check.",
    tip: 'In Logic category, use if statement with bot.is_harvestable from Check category to harvest ready crops.',
    concept: "if",
    goal: 1,
    rewards: { exp: 50, coins: 40, unlocks: ["jump", "is_bug", "is_fire", "is_dead"] },
    prereq: ["cs_loop_0"],
  },
  "cs_grid_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Dynamic Grid Boundary Traversal",
    description: "Use rows and columns functions to determine farm grid dimensions.",
    tip: 'In Math category, use rows and columns in loop bounds so your code adapts when land expands.',
    goal: 1,
    rewards: { exp: 60, coins: 50, unlocks: ["upgrade_bot_action", "upgrade_bot_move", "upgrade_bot_check", "bot"] },
    prereq: ["cs_if_0"],
  },
  "cs_jump_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Targeted Tile Navigation",
    description: "Jump directly to specific tile coordinates.",
    tip: 'In Bot category, use bot.jump to teleport directly to any valid grid coordinate.',
    goal: 1,
    rewards: { exp: 70, coins: 60 },
    prereq: ["cs_grid_0"],
  },
  "cs_pest_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Pest Defense Algorithm",
    description: "Detect and eliminate crop pests.",
    tip: 'In Check category, use bot.is_bug inside an if statement, then call bot.kill_bug from Farm category.',
    goal: 1,
    rewards: { exp: 80, coins: 70, unlocks: ["kill_bug", "bug"] },
    prereq: ["cs_if_0"],
  },
  "cs_fire_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Emergency Fire Suppression",
    description: "Detect and extinguish farm fires.",
    tip: 'In Check category, use bot.is_fire inside an if statement, then call bot.extinguish from Farm category.',
    goal: 1,
    rewards: { exp: 90, coins: 80, unlocks: ["extinguish", "fire"] },
    prereq: ["cs_pest_0"],
  },
  "cs_cleanup_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Wasted Crop Clearing",
    description: "Inspect for withered plants and clear them.",
    tip: 'In Check category, use bot.is_dead inside an if statement, then call bot.destroy from Farm category.',
    goal: 1,
    rewards: { exp: 100, coins: 90 },
    prereq: ["cs_fire_0"],
  },
  "cs_wait_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Growth Cycle Timing",
    description: "Pause bot execution while crops develop.",
    tip: 'In Bot category, use bot.wait to pause execution while waiting for crop growth.',
    goal: 1,
    rewards: { exp: 110, coins: 100, unlocks: ["wait"] },
    prereq: ["cs_cleanup_0"],
  },
  "cs_random_0": {
    type: QuestTypes.CS_CONCEPT,
    title: "Adaptive Farming Decisions",
    description: "Generate random numbers for non deterministic farm logic.",
    tip: 'In Math category, use randint or randfloat to create dynamic decision thresholds.',
    goal: 1,
    rewards: { exp: 120, coins: 110, unlocks: ["randint", "randfloat"] },
    prereq: ["cs_wait_0"],
  },

  // Dedicated Shop Quests
  "shop_seed_0": {
    type: QuestTypes.SHOP,
    title: "Seed Procurement",
    description: "Purchase seed packs from the shop.",
    tip: 'In Shop category, use shop.buy_seed or purchase seeds directly in the shop interface.',
    goal: 1,
    rewards: { exp: 40, coins: 25 },
    prereq: ["cs_loop_0"],
  },
  "shop_land_0": {
    type: QuestTypes.SHOP,
    title: "Farmland Expansion",
    description: "Expand farm size by buying a row or column.",
    tip: 'In Shop category, use shop.buy_row or shop.buy_column to increase grid capacity for larger loops.',
    goal: 1,
    rewards: { exp: 75, coins: 50 },
    prereq: ["cs_grid_0"],
  },
  "shop_upgrade_0": {
    type: QuestTypes.SHOP,
    title: "Robot Performance Tuning",
    description: "Purchase a speed upgrade for your bot.",
    tip: 'In Shop category, use shop.upgrade_bot_action or shop.upgrade_bot_move to execute algorithms faster.',
    goal: 1,
    rewards: { exp: 100, coins: 75 },
    prereq: ["shop_land_0"],
  },

  // Crop Quests
  "crop_wheat_1": {
    type: QuestTypes.CROP,
    title: "Wheat Harvest Mastery",
    description: "Harvest wheat 5 times.",
    tip: 'In Loops category, combine repeat block with bot.till, bot.plant wheat, bot.water, and bot.harvest.',
    goal: 5,
    rewards: { exp: 50, coins: 30, unlocks: [CropTypes.CORN] },
    prereq: ["tut_2"],
  },
  "crop_corn_1": {
    type: QuestTypes.CROP,
    title: "Corn Cluster Harvesting",
    description: "Harvest corn 10 times.",
    tip: 'In Farm category, use bot.plant corn to place corn in adjacent clusters for growth synergy.',
    goal: 10,
    rewards: { exp: 100, coins: 60, unlocks: [CropTypes.RICE] },
    prereq: ["crop_wheat_1"],
  },
  "crop_rice_1": {
    type: QuestTypes.CROP,
    title: "High Yield Rice Cultivation",
    description: "Harvest rice 10 times.",
    tip: 'In Farm and Check categories, combine bot.plant rice with bot.is_bug to protect high profit crops.',
    goal: 10,
    rewards: { exp: 150, coins: 90, unlocks: [CropTypes.POTATO] },
    prereq: ["crop_corn_1"],
  },
  "crop_potato_1": {
    type: QuestTypes.CROP,
    title: "Potato Underground Farming",
    description: "Harvest potato 10 times.",
    tip: 'In Farm and Bot categories, use bot.plant potato and bot.wait to manage slow growing tuber cycles.',
    goal: 10,
    rewards: { exp: 200, coins: 120, unlocks: [CropTypes.SUGARCANE] },
    prereq: ["crop_rice_1"],
  },
  "crop_sugarcane_1": {
    type: QuestTypes.CROP,
    title: "Sugarcane Regrowth Loop",
    description: "Harvest sugarcane 10 times.",
    tip: 'In Loops category, use while loop with bot.harvest to continuously harvest regrowing sugarcane.',
    goal: 10,
    rewards: { exp: 250, coins: 150, unlocks: [CropTypes.TOMATO] },
    prereq: ["crop_potato_1"],
  },
  "crop_tomato_1": {
    type: QuestTypes.CROP,
    title: "Fresh Tomato Harvesting",
    description: "Harvest tomato 10 times.",
    tip: 'In Check category, use bot.is_harvestable inside a fast inspection loop to harvest tomatoes before spoilage.',
    goal: 10,
    rewards: { exp: 300, coins: 200 },
    prereq: ["crop_sugarcane_1"],
  }
};
